### ISSUE TITLE
How Can I Used in another nodejs framework

### ISSUE THREAD

**Issue by sunjiongjun** [cube-js/cube.js#1343]
i want use koa / eggjs , how can i use ?

**Comment by keydunov** [comment]
Hi @sunjiongjun, 

We spent some time figuring out our relationship with embedding Cube.js into existing Node.js applications with frameworks like express, koa, etc. What we find out is Cube.js should be scaled very differently rather than other parts of the big express app. Even if small to medium deployments work in this configuration it's a dead-end in terms of devops and infrastructure in long term.

Given that we decided to deprecate express embedding support and recently shipped several major updates to Cube.js which significantly change Cube.js-express relationship.

Moving forward, we recommend running Cube.js as a separate microservice. Feel free to join [our Slack](https://slack.cube.dev/) and reach out to the core team there for more best practices and advice.
