### ISSUE TITLE
Query with many filter values ends up in 413 URL too large

### ISSUE THREAD

**Issue by Lozzi** [cube-js/cube.js#1558]
**Problem**

I ran into an issue when querying with a filter that had a lot of long string values that the request URL was too large [error 413](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413#:~:text=The%20HTTP%20413%20Payload%20Too,a%20Retry%2DAfter%20header%20field).

The request is 4534 characters in legnth.

In a previous project we implemented a check for the length of the query and if it exceeded 2048 characters we did a POST with body instead of the usual GET request.

Is there any work around for this currently in Cube or has anyone ran into the same issue?

**Comment by hassankhan** [comment]
Hi @Lozzi, you can [use the `POST` method](https://cube.dev/docs/rest-api#api-reference-v-1-load) to send queries to Cube.js.

**Comment by ovr** [comment]
@hassankhan Our `@cubejs-client/core` is doing everything by GET method inside Request, I think we should prepare a fix for that.

**Comment by Lozzi** [comment]
@ovr Yes, forgot to mention that I'm using the @cubejs-client/core to make the requests. I could try to take a look at it and submit a Pull Request over the holidays.

**Comment by hassankhan** [comment]
@Lozzi That would be amazing 😄

**Comment by telunc** [comment]
We ran into this issue with our Angular app. Our angular app initialize client in app.module with forRoot meaning that client is initialized once at start. In HttpTransport, `this.method = this.method || (url.length < 2000 ? 'GET' : 'POST');` the later url length logic will only get run once if method is undefined. Any request afterwards will be taken from `this.method`.

We can't pass in `POST` directly in client option as well since Meta is a `GET` endpoint.
