### ISSUE TITLE
"Illegal input character" when using originalSql pre-aggregation with BigQuery and USER_CONTEXT

### ISSUE THREAD

**Issue by landyrev** [cube-js/cube.js#197]
**Describe the bug**
OriginalSql pre-aggregation fails when cube sql contains USER_CONTEXT

**To Reproduce**
1. Create simple cube with with originalSql pre-aggregation and USER_CONTEXT used in query ([example](https://gist.github.com/landyrev/e10d41f8202dc409410c0653892187bd))
2. Try to make simple query ([example](https://gist.github.com/landyrev/f44fc5f1dd5a3bec51e1628abf68d28c))
3. Get ["Illegal input character" error](https://gist.github.com/landyrev/157be94ab570c943f7150b6ab8451144)

**Version:**
0.10.30

**Comment by paveltiunov** [comment]
@landyrev Thanks for posting this! This is interesting one. So `originalSql` pre-aggregation doesn't support `USER_CONTEXT` or any other context variables because it's prepared without context. The best we can do here is to provide correct error message instead of this `Illegal input character` message and add note to the docs.

To take advantage of pre-aggregations in multi tenancy environment you can consider using `queryTransformer`: https://cube.dev/docs/@cubejs-backend-server-core#options-reference-query-transformer

**Comment by landyrev** [comment]
Looks interesting.

So `queryTransformer` is being applied to all queries, even to external ones?

**Comment by paveltiunov** [comment]
@landyrev Yeah. Every query is passed through `queryTransformer` before it'll be actually processed. This function also receives user context so it's a good place for security checks.
