### ISSUE TITLE
Feature request: metadata (age, cache hit/miss) of the results returned

### ISSUE THREAD

**Issue by gane5h** [cube-js/cube.js#203]
**Is your feature request related to a problem? Please describe.**
When a user loads a query, it isn't clear if these are fresh results, or from the cache preAggregated table. We need to display metadata on the results so that the user can make a decision to continue with the analysis or kick-start a refresh (outside the scope of this issue.)

**Describe the solution you'd like**
The `load` result should have metadata on the when the query was run, whether it came from a cache or preAggregation, etc.

**Describe alternatives you've considered**
No alternatives at the moment.

**Comment by paveltiunov** [comment]
@gane5h Hey Ganesh! Thanks for posting this! I think we can add something like `loadTimestamp` to the response. It'll be hard to say whether it comes from pre-aggregation or cache because it always comes from two of these sources. `loadTimestamp` will be always defined as `min(cacheTimestamp, preAggregationTimestamp)`. Not sure if we need to provide two of these timestamps to client. Would love to hear your thoughts on this.

**Comment by gane5h** [comment]
Hey @paveltiunov – I think just one timesatmp `loadTimestamp` will be sufficient for display purposes. Thanks.

**Comment by paveltiunov** [comment]
Available as `lastRefreshTime` in `load` response.
