### ISSUE TITLE
Support for External Pre-aggregation without writing to DB (MongoDB case)

### ISSUE THREAD

**Issue by MuhammadMattiullah** [cube-js/cube.js#239]
I am trying to use pre-aggregation feature of cube js which is indeed very helpful. I am using mongodb and connecting it with mongodb connectorBI i.e mongosqld. 
I have created a pre-aggregation query but it's not working and not creating any pre-aggregation tables as well.  
Adding a support of pre-aggregation on mongosqld or anyother mongodb connectorBI.

**Comment by paveltiunov** [comment]
@MuhammadMattiullah Thanks for creating this one! Here we should support download of pre-aggregations data without creating tables in main DB because MongoDB BI connector doesn't allow to create tables.

**Comment by MuhammadMattiullah** [comment]
@paveltiunov can you tell me how much time will it take to implement this feature ? 
Any rough estimation ? 
So i can integrate this feature in future project.

**Comment by paveltiunov** [comment]
@MuhammadMattiullah Great question! So to implement it we'd need just to download results here: https://github.com/cube-js/cube.js/blob/master/packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js#L325 
instead of creating a table and pass here:
https://github.com/cube-js/cube.js/blob/master/packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js#L336
This should should be fallback behavior so I think driver can provide some boolean method like `supportsPreAggregationTables()` to check if it has this capability.

So overall not a lot of changes but it's not on our road map though. It'd great if someone else can pickup it.
