### ISSUE TITLE
Connecting to MSSQL with docker image needs ability to enable trustedconnection

### ISSUE THREAD

**Issue by ecolara3** [cube-js/cube.js#2996]
**Describe the bug**
When setting-up cube using docker and following the instructions, there is no ability to enable trusted connection without modifying the config files which are not available until after you connect to the DB.

**To Reproduce**
1. Follow instructions using a MSSQL database with trusted connection required ([tutorial](https://cube.dev/docs/getting-started/docker))

**Expected behavior**
To be able to connect to a MSSQL database

**Screenshots**
![image](https://user-images.githubusercontent.com/3268879/123062048-cc0d9580-d3d1-11eb-9053-9cd70e38ce6a.png)

**Version:**
[e.g. 0.4.5]

**Additional context**
I know Cube works with the node version, but the docker container doesn't seem to work and I cannot modify the config file since it is not created yet

**Comment by ecolara3** [comment]
Thanks guy for looking into this!

**Comment by ryanpei** [comment]
hello @ecolara3 - we have updated the workflow for Docker such that you can add a config file to your Docker's mount volume and have that applied to your cube API instance upon start-up. You can therefore skip this DB connection step in the UI if you have this configured in your `.env` file as you would with the node version.

Hope this works for you now! Let me know if otherwise.

**Comment by ecolara3** [comment]
Hell yeah that works! Thanks a ton! Awesome framework btw!

**Comment by ryanpei** [comment]
great to hear, thank you for raising this issue!
