### ISSUE TITLE
Playground doesn't load on 0.28.31

### ISSUE THREAD

**Issue by thellimist** [cube-js/cube.js#3386]
**Describe the bug**

I get white screen and 
```Could not load content for http://localhost:3000/PlaygroundQueryBuilder/QueryBuilderContainer.tsx (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)```

**Expected behavior**

The playground should work

**Screenshots**

![](https://cdn.zappy.app/6b599dc00b002bb982df38011ef39695.png)

**Version:**
Playground 0.28.31
cubejs/cube:v0.28.28 (note the server's playground works fine)

**Comment by paveltiunov** [comment]
@thellimist Hey Kan! Are you building a playground yourself?

**Comment by thellimist** [comment]
> @thellimist Hey Kan! Are you building a playground yourself?

Yes, we use the playground package internally inside our application.

**Comment by paveltiunov** [comment]
@thellimist According to the error it fails due to an undefined history object. I guess at that point you'd need to debug to figure out what's causing it. It might be it interferes with other parts of your project which use location also. Embedding the playground isn't something we fully support currently but we're open to PRs fixing embedding edge cases.

**Comment by thellimist** [comment]
This was solved by updating playground versions

**Comment by thellimist** [comment]
> @thellimist Embedding the playground isn't something we fully support currently but we're open to PRs fixing embedding edge cases.

Do you have a todo list/project definition for this?
