### ISSUE TITLE
Filters with multiple values miss pre-aggregation matching

### ISSUE THREAD

**Issue by kirill-morozov-bidstack** [cube-js/cube.js#3632]
**Describe the bug**
I have just a regular pre-aggregation, and when I set more than 1 value in filter it fails to match it, falling over to BigQuery query

**To Reproduce**
1. Create pre-aggregation with measure and dimension
2. Go to playground
3. Select measure and select dimension from pre-aggregation as a filter with setting any value (but just one)
3a. Click on SQL tab
3b. You'll see that query is built to fetch data from pre-aggregation
4. Select measure and select dimension from pre-aggregation as a filter with setting multiple values
5. Click on SQL tab
6. You'll see that query now built avoiding pre-aggregation

**Expected behavior**
When multiple values set I'd expect it still fetch data from pre-aggregation

**Screenshots**
![image](https://user-images.githubusercontent.com/54888193/140514811-f3dd411a-fcfb-456c-80c7-38534a08cbc4.png)
![image](https://user-images.githubusercontent.com/54888193/140514847-2a6c8905-38e4-440d-b17c-347445a221c2.png)

**Version:**
[e.g. 0.28.53]

**Additional context**
Happens with previous versions as well

**Comment by rpaik** [comment]
@ovr @paveltiunov can you take a look 👆?

**Comment by paveltiunov** [comment]
@kirill-morozov-bidstack Hey Kirill! This is expected behavior however I believe it isn't described in docs yet. The problem here is `totalUniqueUsers` is most probably a non-additive measure and you can apply two filter values only if you have selected this dimension as part of the query. Otherwise, there's just no way to derive the result you want to get because the sum of two distinct counts isn't always a distinct count of the union. cc @hassankhan @igorlukanin

**Comment by kirill-morozov-bidstack** [comment]
@paveltiunov Hey Pavel! Oh, I see, okay, it does make sense, thanks!
