### ISSUE TITLE
Unable to load @cubejs-backend/native, probably your system (x64-darwin) is not supported. when trying to use the sql api.

### ISSUE THREAD

**Issue by enzo-pellegrini** [cube-js/cube.js#3713]
**Describe the bug**
I have a working cubejs project, with some schemas, in dev mode, installed with npx without a docker. 
I'm using mac os monterey, but I tried the same thing on an ubuntu machine (64 bit) and I got the same error, with a different architecture in the error message: `Error: Unable to load @cubejs-backend/native, probably your system (x64-darwin) is not supported.` I also tried installing the @cubejs-backend/native package but to no avail.
Just adding the CUBE_SQL_USERNAME enviromental variable triggers the problems, and it goes away as soon as I stop using that variable.

**To Reproduce**
Create a blank project on ubuntu or mac os. Set the CUBE_SQL_USERNAME variable. Run `yarn dev`.

**Version:**
├── @cubejs-backend/mysql-driver@0.28.58
├── @cubejs-backend/native@0.28.58
└── @cubejs-backend/server@0.28.58

**Comment by ovr** [comment]
Hello @enzo-pellegrini ,

What version of Node.js do you use?

Thanks

**Comment by enzo-pellegrini** [comment]
version 17.0.1 on Mac 
v. 12.22.5 on Linux

**Comment by enzo-pellegrini** [comment]
Can I ask what version of node I should use to try this feature? Node 16?
Also can this info be added in the docs? I found no mention of this

**Comment by enzo-pellegrini** [comment]
I am probably doing something wrong, but I used nvm to change node version, opening node shell shows version 16.13.0, I deleted the node_modules directory, installed @cubejs/native when asked, but it still crashes with the same system not supported error

**Comment by ovr** [comment]
Support for Node.js 17 was released in `v0.28.60`,

@enzo-pellegrini can you try with the latest version?

Thanks

**Comment by enzo-pellegrini** [comment]
I tried with the latest version but I got the same results,
```
 npm run dev

> analytics_dashboard@0.0.1 dev
> cubejs-server

🔥 Cube Store (0.28.60) is assigned to 3030 port.
🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
🦅 Dev environment available at http://localhost:4000
Fatal error during server start:
Error: Unable to load @cubejs-backend/native, probably your system (x64-darwin) with Node.js v17.0.1 is not supported.
    at loadNative (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@cubejs-backend/native/js/index.ts:42:11)
    at Object.setLogLevel (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@cubejs-backend/native/js/index.ts:82:20)
    at new SQLServer (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@cubejs-backend/api-gateway/src/sql-server.ts:22:5)
    at ApiGateway.initSQLServer (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:464:12)
    at CubejsServerCore.initSQLServer (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@cubejs-backend/server-core/src/core/server.ts:557:23)
    at CubejsServer.listen (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@cubejs-backend/server/src/server.ts:115:36)
    at ServerContainer.runServerInstance (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@cubejs-backend/server/src/server/container.ts:240:35)
    at makeInstance (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@cubejs-backend/server/src/server/container.ts:344:22)
    at ServerContainer.start (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@cubejs-backend/server/src/server/container.ts:357:20)
    at Server.run (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@cubejs-backend/server/src/command/server.ts:25:5)
    at Server._run (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@oclif/command/lib/command.js:43:20)
    at Config.runCommand (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@oclif/config/lib/config.js:173:24)
    at Main.run (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@oclif/command/lib/main.js:27:9)
    at Main._run (/Users/enzo/Coding/threek/Team-Waste/analytics_dashboard/node_modules/@oclif/command/lib/command.js:43:20)

❯ npm list
analytics_dashboard@0.0.1 /Users/enzo/Coding/threek/Team-Waste/analytics_dashboard
├── @cubejs-backend/mysql-driver@0.28.60
├── @cubejs-backend/native@0.28.60
└── @cubejs-backend/server@0.28.60
```

**Comment by ranrao** [comment]
I'm running into the same issue. Any ideas @enzo-pellegrini or @ovr? Thank you

**Comment by ovr** [comment]
@ranrao can you post an error message? Probably, it's not supported.  Thanks

**Comment by ranrao** [comment]
@ovr, thank you for your prompt response. Here is what my output. Appreciate any alternatives. Thanks so much 

` ~w/Cube/ npx cubejs-cli create hello-world -d postgres
npx: installed 209 in 14.302s
- Creating project structure
- Installing server dependencies
npm WARN deprecated @hapi/joi@17.1.1: Switch to 'npm install joi'
npm WARN deprecated @hapi/address@4.1.0: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/formula@2.0.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated @hapi/pinpoint@2.0.0: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> @cubejs-backend/native@0.29.18 install /Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@cubejs-backend/native
> node-pre-gyp install || echo 'Your system is not supported by @cubejs-backend/native, some feature will be unavailable.'

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: ENOENT: no such file or directory, open '/Users/ranjanimanjunath/bundle.pem'
node-pre-gyp ERR! stack     at Object.openSync (fs.js:498:3)
node-pre-gyp ERR! stack     at Object.readFileSync (fs.js:394:35)
node-pre-gyp ERR! stack     at place_binary (/Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@mapbox/node-pre-gyp/lib/install.js:45:27)
node-pre-gyp ERR! stack     at /Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@mapbox/node-pre-gyp/lib/install.js:216:11
node-pre-gyp ERR! System Darwin 19.5.0
node-pre-gyp ERR! command "/Users/ranjanimanjunath/.nvm/versions/node/v14.17.5/bin/node" "/Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@cubejs-backend/native
node-pre-gyp ERR! node -v v14.17.5
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok 
ENOENT: no such file or directory, open '/Users/ranjanimanjunath/bundle.pem'
Your system is not supported by @cubejs-backend/native, some feature will be unavailable.

> @cubejs-backend/cubestore@0.29.18 postinstall /Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@cubejs-backend/cubestore
> node bin/post-install


Cube.js Cube Store Installer ---------------------------------------

Error: Cube Store v0.29.18 Artifact for darwin is not found. Most probably it is still building. Please try again later.
    at Object.downloadBinaryFromRelease (/Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@cubejs-backend/cubestore/js-wrapper/src/download.ts:87:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /Users/ranjanimanjunath/Documents/Workspace/Cube/hello-world/node_modules/@cubejs-backend/cubestore/js-wrapper/src/post-install.ts:12:7

Need some help? -------------------------------------

  Ask this question in Cube.js Slack: https://slack.cube.dev
  Post an issue: https://github.com/cube-js/cube.js/issues

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @cubejs-backend/cubestore@0.29.18 postinstall: `node bin/post-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @cubejs-backend/cubestore@0.29.18 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ranjanimanjunath/.npm/_logs/2022-01-10T07_51_52_838Z-debug.log

Cube.js Error ---------------------------------------

Error: npm install --save-dev @cubejs-backend/server failed with exit code 1
    at ChildProcess.<anonymous> (/Users/ranjanimanjunath/.npm/_npx/80897/lib/node_modules/cubejs-cli/src/utils.ts:14:16)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

Need some help? -------------------------------------

  Ask this question in Cube.js Slack: https://slack.cube.dev
  Post an issue: https://github.com/cube-js/cube.js/issues

 ~w/Cube/ node -v
v14.17.5
`

**Comment by ovr** [comment]
@ranrao Should be fixed now, can you try again? Thanks

**Comment by ranrao** [comment]
@ovr: It works now! Excellent! Thanks so much for the quick update. 🎉

**Comment by johanjvrens** [comment]
I get the exact same issue when I use npm _v16.13.2_ and add `CUBEJS_SQL_PORT=3306` to **.env** when I remove the aforementioned from the **.env** it works again.

`CUBEJS_SQL_PORT=3306` in **.env** works fine with  _v14.19.0_ 

Any ideas?
