### ISSUE TITLE
Is there a way to connect Cube.js with MongoDB Community Edition? 

### ISSUE THREAD

**Issue by ninode97** [cube-js/cube.js#3723]
**Problem**

In order to use MongoDB with Cube.js there is a need to have BI connector.

Currently MongoDB BI connector is available for Atlas or Enterprise edition.

The question would be if there is a way to use Cube.js with MongoDB Community Edition?

**Comment by igorlukanin** [comment]
Hi @ninode97 👋 

> In order to use MongoDB with Cube.js there is a need to have BI connector.

Indeed, BI Connector is mandatory for connecting to MongoDB because Cube uses SQL to query databases. SQL support for MongoDB is provided via its BI Connector.

As a workaround, you might want to replicate data from MongoDB to another database using a ETL tool, e.g., something like [Airbyte](http://airbyte.io). However, IDK how practical that is for your use case.
