### ISSUE TITLE
Update of API BasePath does not apply for playground: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by claireckc** [cube-js/cube.js#377]
**Describe the bug**
By explicitly defining a `basePath` in the ServerCore options, playground will still call the default basePath of '/cubejs-api'.

**To Reproduce**
1. Go to where CubeJsServerCore is initiated
2. Define a `basePath` in the options
3. Run `node index.js`
4. Head to localhost:9000 and an error message toast will appear stating an error has occurred
5. Open network console and `http://localhost:9000/cubejs-api/v1/meta` is being called

**Expected behavior**
Playground should be making a network call to `http://localhost:9000/<defined basePath>/v1/meta` instead of the default basePath

**Screenshots**
![image](https://user-images.githubusercontent.com/19924541/74510081-f168d480-4f3d-11ea-88f4-d1a9cc4783ad.png)

**Version:**
0.15.3

**Additional context**

**Comment by paveltiunov** [comment]
@claireckc Hey Claire! Thanks for posting this one! 

For someone who wants to contribute a fix here's a line that fetches apiUrl from server:
https://github.com/cube-js/cube.js/blob/94ca91bcbe055a4a93eed8b3b9846644cc44142e/packages/cubejs-playground/src/ExplorePage.js#L21
We should provide `basePath` here instead of absolute URL because only client knows accessible host of playground server through `window.location`.

**Comment by nuwe1** [comment]
@paveltiunov I am interested in working on this could you please elaborate more on what needs to be done
