### ISSUE TITLE
`NODE_ENV` usage conflict when embedding into existing application

### ISSUE THREAD

**Issue by shamil** [cube-js/cube.js#3842]
**Problem**

We are embedding `cubejs` into our application using `@cubejs-backend/server-core`

Our application uses `NODE_ENV` to set the running env, and we have several environments. Currently `cubejs` requires `NODE_ENV` to be set to `production` in order to run in production mode. Our environments have different names than `production` which means we can't make `cubejs` run in production mode.

My question is, how can I avoid the  conflict of `NODE_ENV`.  I want `cubejs` to run in production mode, but not set `NODE_ENV` to `production`. Is it possible?

**Comment by ivan-vdovin** [comment]
Hi @shamil!
As I know, the best practice for NODE_ENV var usage in Node apps is only to have production or development values:
https://nodejs.dev/learn/nodejs-the-difference-between-development-and-production
https://stackoverflow.com/questions/16978256/what-is-node-env-and-how-to-use-it-in-express

Then maybe it makes sense to use some other var for your multiple envs. Something like APP_ENV:
https://stackoverflow.com/a/53368078/17564169

If that's not what you can do right now maybe it makes sense to use Cube as a separate service in docker. Also embedding Cube within Express may not be the best option because it might lead to various issues. Please see this [blog post for details](https://cube.dev/blog/cubejs-loves-docker/). Also, [there’s a migration guide](https://cube.dev/docs/configuration/overview#migrating-from-express-to-docker).
