### ISSUE TITLE
api-gateway: TS compilation error (files missing from NPM package)

### ISSUE THREAD

**Issue by mfulop** [cube-js/cube.js#4536]
**Describe the bug**
The API Gateway npm package is missing files from src/types. [The source folder](https://github.com/cube-js/cube.js/tree/master/packages/cubejs-api-gateway/src/types) includes several .d files which are missing from the published package, causing compilation errors in TS environments.

**Version:**
0.29.57

**Comment by eugene1g** [comment]
Yep, all `*.d.ts` files are not included in the `dist` bundle (see https://www.unpkg.com/browse/@cubejs-backend/api-gateway@0.30.2/dist/src/types/) and only `enum.ts` exists.

Typescript does not copy `.d.ts` files during the build process because it does not transpile them. The solution is to either copy those files manually (during the build), or rename them to `.ts` so `tsc` picks them up.

**Comment by parkerself22** [comment]
@buntarb Any timeline on this getting fixed?

**Comment by frolovdev** [comment]
@parkerself22 @eugene1g @mfulop

hi there, hope you're doing great; please check this out #5132 🙏
