### ISSUE TITLE
Integrate this playground in my existing react/next js project

### ISSUE THREAD

**Issue by BSuthar712** [cube-js/cube.js#4567]
**Trying to integrate this project into my existing next js project**

I can see in the description we can just embed components that the playground project provides into our existing one. 
could you please provide a detailed guide to do so?

I tried to follow the readme file but It is not working!
https://github.com/cube-js/cube.js/tree/master/packages/cubejs-playground

Thanks a lot in advance!

**Comment by ivan-vdovin** [comment]
Hi @BSuthar712 !
First of all, let me recommend migrating your Express-based deployment of Cube to Docker. Embedding Cube within Express is not recommended because it might lead to various issues. Please see this [blog post](https://cube.dev/blog/cubejs-loves-docker/) for details. Also, there’s a [migration guide](https://cube.dev/docs/configuration/overview#migrating-from-express-to-docker).

As for your question, I would like to know what exactly doesn't work. Could you share more details here, please?

**Comment by BSuthar712** [comment]
Hi @ivan-vdovin 
Thanks a lot for your response.

I am not trying to use that in express.
I am trying to embed this in my next js application. Basically, in react js. 
Could you please help me out with this?

Thanks a lot in advance!

**Comment by paveltiunov** [comment]
@BSuthar712 Playground embedding is possible but not supported by the Cube team. Please feel free to provide PRs with fixes.
