### ISSUE TITLE
Sql api. How one can hide specific cube?

### ISSUE THREAD

**Issue by NikKomarov** [cube-js/cube.js#5219]
**Problem**

I want to remove cubes from sql api, but leave it visible via rest api.
In other words, remove some cubes from result of query
```
SELECT * FROM information_schema.tables
where table_schema like 'public'
```
Is there any way to do it?

**Comment by ivan-vdovin** [comment]
@ovr wdyt?

**Comment by paveltiunov** [comment]
@NikKomarov We're going to provide `shown` flag for cubes which can be used together with https://cube.dev/docs/config#check-sql-auth in order to provide desired behavior through dynamic schemas. Right now, you can achieve pretty same behavior by hiding all members of the specific cube.

It'd be done as part of #5044 .
