### ISSUE TITLE
Playground only shows about 40 tables in schema creation

### ISSUE THREAD

**Issue by davemaier** [cube-js/cube.js#738]
**Describe the bug**
When I add a mysql DB with more then 40 tables, cubejs playground only shows me the first 40 tables. I can't find any documentation on if this behavior is configurable, therefore I assume it is a bug.

**To Reproduce**
1. Create a new Project with a large mysql DB as datasource. My setup is running on mysql server 5.7.30.
2. Go to http://localhost:4000/#/schema and open the database in the left side panel. 

**Expected behavior**
I'd expect to get a list of ALL tables contained in my database. 

**Version:**
"@cubejs-backend/mysql-driver": "^0.19.17",
"@cubejs-backend/server": "^0.19.33"

**Comment by Lifeuser** [comment]
I have the same thing with **cubejs-cli@0.19.35**.

I did some research just to get familiar on how the code is structured. 
I am pretty sure that the bug is in the playground app build that comes with [@cubejs-backend/server-core](https://www.npmjs.com/package/@cubejs-backend/server-core) (0.19.36) npm package.
I built the playground app myself and ran **cubejs-cli** from source with all of the necessary packages linked by yarn.
The bug goes away. 

You probably just need to rebuild it and republish the **server-core** with the new version.
I hope this helps.

**Comment by RusovDmitriy** [comment]
Failed to reproduce error, i tried repeat this bug in next variation:

- 3 diff database (postgres, mysql, clickhouse):latest with current versions 0.19.61
- 1 database (mysql: 5.7.30) with issues versions: 
      "@cubejs-backend/mysql-driver": "^0.19.17", 
      "@cubejs-backend/server": "^0.19.33",
      "cubejs-cli@0.19.33"

Also i checked next scripts chain and git history, but found no problem: 

- https://github.com/cube-js/cube.js/blob/master/packages/cubejs-playground/src/SchemaPage.js#L74
- https://github.com/cube-js/cube.js/blob/master/packages/cubejs-server-core/core/DevServer.js#L55
- https://github.com/cube-js/cube.js/blob/master/packages/cubejs-query-orchestrator/driver/BaseDriver.js#L82

@davemaier You could make repository with reproduce this bug and share link, but i think fast way it is bump your packages versions

**Comment by davemaier** [comment]
Hi, thank you for trying to reproduce the problem. I've now bumped my core package to "@cubejs-backend/server": "^0.20.10" and it seems like everything works just as it should. 
I think this issue can be closed now.
